### ISSUE TITLE
Android screenshot can not be shown in center agent page

### ISSUE THREAD

**Issue by Stephen0910** [microsoft/HydraLab#257]
**Issue:**
In center agent web page, the Android  devices screenshot is broken.
Could you do me a favor?
![image](https://user-images.githubusercontent.com/26613645/217190333-f9142e90-eaca-4c5d-afe0-d5cb473f64c0.png)

**version:**
versionName=1.7.0.153478

*"OS:"*
ubuntu 18

**Agent log:**  by hydra_lab_current.log
2023-02-07 16:05:27,898 INFO (c.m.h.a.s.AgentWebSocketClientService - AgentWebSocketClientService.java:61)[WebSocketConnectReadThread-20] - onMessage Receive bytes message Message(method=GET, sessionId=null, code=0, message=null, agentId=null, type=null, path=/api/device/list, params=null, body=null, bodyType=null)
2023-02-07 16:05:27,899 WARN (c.m.h.a.r.DeviceTaskControlExecutor - DeviceTaskControlExecutor.java:34)[WebSocketConnectReadThread-20] - All device count 1
2023-02-07 16:05:27,910 INFO (c.m.h.a.s.DeviceControlService - ADBOperateUtil.java:111)[ScreenshotExecutor1] - >> adb -s 8UR4C19C16012215 shell input keyevent KEYCODE_WAKEUP
2023-02-07 16:05:28,242 INFO (c.m.h.c.u.ADBOperateUtil - ADBOperateUtil.java:88)[ScreenshotExecutor1] - getScreenshot
2023-02-07 16:05:30,001 ERROR (c.m.h.c.m.DeviceStabilityMonitor - DeviceStabilityMonitor.java:148)[scheduling-1] - [Stability] State change window of device 8UR4C19C16012215 is null
2023-02-07 16:05:31,346 INFO (c.m.h.c.u.b.BlobStorageClient - BlobStorageClient.java:143)[ScreenshotExecutor1] - Get a BlobContainerClient for container images for file D:\Tools\Hydra_Agent_Installer_Windows\storage\devices\screenshot\huawei-oxf_an00-8UR4C19C16012215-8UR4C19C16012215.jpg
2023-02-07 16:05:32,518 ERROR (c.m.h.c.m.i.AndroidDeviceManager - AndroidDeviceManager.java:430)[Device List Monitor] - Status code 404, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerNotFound</Code><Message>The specified container does not exist.
RequestId:715ebd93-901e-0039-19ca-3a1be2000000
Time:2023-02-07T08:05:33.0571960Z</Message></Error>"
com.azure.storage.blob.models.BlobStorageException: Status code 404, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerNotFound</Code><Message>The specified container does not exist.
RequestId:715ebd93-901e-0039-19ca-3a1be2000000
Time:2023-02-07T08:05:33.0571960Z</Message></Error>"
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at com.azure.core.http.rest.RestProxy.instantiateUnexpectedException(RestProxy.java:365)
	at com.azure.core.http.rest.RestProxy.lambda$ensureExpectedStatus$5(RestProxy.java:405)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:337)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:354)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398)
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onSubscribe(MonoCacheTime.java:293)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:192)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:143)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:130)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:119)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:130)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:184)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:128)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:142)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:400)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:419)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:473)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:684)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1372)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1235)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1284)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:835)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1704)
		at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:128)
		at com.azure.storage.blob.BlobClient.uploadFromFileWithResponse(BlobClient.java:389)
		at com.azure.storage.blob.BlobClient.uploadFromFile(BlobClient.java:361)
		at com.azure.storage.blob.BlobClient.uploadFromFile(BlobClient.java:334)
		at com.microsoft.hydralab.common.util.blob.BlobStorageClient.uploadBlobFromFile(BlobStorageClient.java:151)
		at com.microsoft.hydralab.common.management.impl.AndroidDeviceManager.getScreenShot(AndroidDeviceManager.java:393)
		at com.microsoft.hydralab.common.management.impl.AndroidDeviceManager.deviceInfoUpdate(AndroidDeviceManager.java:428)
		at com.microsoft.hydralab.common.management.impl.AndroidDeviceManager$1.deviceConnected(AndroidDeviceManager.java:63)
		at com.android.ddmlib.AndroidDebugBridge.deviceConnected(AndroidDebugBridge.java:966)
		at com.android.ddmlib.DeviceMonitor.updateDevices(DeviceMonitor.java:230)
		at com.android.ddmlib.DeviceMonitor.access$500(DeviceMonitor.java:60)
		at com.android.ddmlib.DeviceMonitor$DeviceListUpdateListener.deviceListUpdate(DeviceMonitor.java:708)
		at com.android.ddmlib.DeviceMonitor$DeviceListMonitorTask.processIncomingDeviceData(DeviceMonitor.java:922)
		at com.android.ddmlib.DeviceMonitor$DeviceListMonitorTask.run(DeviceMonitor.java:856)
		... 1 common frames omitted

**Comment by hydraxman** [comment]
Have you provided the correct Azure blob connection string to the service before running it, according to this part https://github.com/microsoft/HydraLab#quick-guide-on-out-of-box-uber-docker-image? @Stephen0910

**Comment by hydraxman** [comment]
Trying to fix this with #267

**Comment by RaccoonLi** [comment]
Our new release has fixed it.
https://github.com/microsoft/HydraLab/releases/tag/Release%401.8.1_154226
